import argparse
from models import resnet
from model import load_pretrained_model
from PIL import Image
from braceexpand import braceexpand
import glob
from spatial_transforms import (Compose, Normalize, Resize, CenterCrop,
                                ToTensor, ScaleValue)
import torch
import torch.nn.functional as F

magic_labels_700 = [
    "slicing onion",
    "jetskiing",
    "building cabinet",
    "eating hotdog",
    "building lego",
    "jumping jacks",
    "kissing",
    "bee keeping",
    "blowing glass",
    "curling eyelashes",
    "shining shoes",
    "flipping pancake",
    "putting on eyeliner",
    "salsa dancing",
    "tasting wine",
    "pinching",
    "massaging back",
    "getting a piercing",
    "bouncing ball (not juggling)",
    "playing gong",
    "karaoke",
    "battle rope training",
    "pumping fist",
    "pretending to be a statue",
    "ski ballet",
    "stretching leg",
    "decoupage",
    "tossing coin",
    "ironing",
    "washing hands",
    "doing laundry",
    "dancing charleston",
    "opening coconuts",
    "opening wine bottle",
    "looking in mirror",
    "cracking neck",
    "springboard diving",
    "golf chipping",
    "repairing puncture",
    "crocheting",
    "talking on cell phone",
    "opening present",
    "leatherworking",
    "pulling rope (game)",
    "giving or receiving award",
    "tiptoeing",
    "eating nachos",
    "catching or throwing baseball",
    "bowling",
    "playing recorder",
    "whistling",
    "parkour",
    "trimming shrubs",
    "exercising arm",
    "clay pottery making",
    "playing controller",
    "playing ukulele",
    "training dog",
    "using segway",
    "roasting pig",
    "shoot dance",
    "throwing snowballs",
    "using remote controller (not gaming)",
    "riding or walking with horse",
    "hugging (not baby)",
    "playing bass guitar",
    "squeezing orange",
    "waxing armpits",
    "recording music",
    "belly dancing",
    "brushing teeth",
    "applying cream",
    "chiseling wood",
    "head stand",
    "directing traffic",
    "photocopying",
    "yawning",
    "checking watch",
    "writing",
    "sausage making",
    "crossing eyes",
    "falling off bike",
    "blending fruit",
    "skiing slalom",
    "pouring wine",
    "throwing tantrum",
    "celebrating",
    "fidgeting",
    "shearing sheep",
    "tagging graffiti",
    "diving cliff",
    "throwing knife",
    "scrapbooking",
    "cartwheeling",
    "hurdling",
    "getting a haircut",
    "slacklining",
    "arm wrestling",
    "playing with trains",
    "mopping floor",
    "scrambling eggs",
    "playing tennis",
    "blowing nose",
    "playing flute",
    "pushing car",
    "vacuuming floor",
    "getting a tattoo",
    "raising eyebrows",
    "abseiling",
    "playing road hockey",
    "headbanging",
    "spraying",
    "chasing",
    "playing billiards",
    "motorcycling",
    "air drumming",
    "changing gear in car",
    "riding unicycle",
    "somersaulting",
    "making snowman",
    "using circular saw",
    "attending conference",
    "massaging feet",
    "playing field hockey",
    "playing scrabble",
    "polishing metal",
    "assembling computer",
    "riding snow blower",
    "news anchoring",
    "flying kite",
    "breakdancing",
    "eating cake",
    "counting money",
    "breathing fire",
    "carving ice",
    "shining flashlight",
    "archaeological excavation",
    "calculating",
    "snatch weight lifting",
    "playing accordion",
    "stacking cups",
    "playing cards",
    "playing badminton",
    "stomping grapes",
    "playing didgeridoo",
    "chiseling stone",
    "folding napkins",
    "snowmobiling",
    "backflip (human)",
    "golf putting",
    "lock picking",
    "lawn mower racing",
    "making the bed",
    "brushing floor",
    "peeling banana",
    "front raises",
    "wood burning (art)",
    "hurling (sport)",
    "long jump",
    "squat",
    "playing checkers",
    "bouncing on trampoline",
    "playing oboe",
    "playing blackjack",
    "kitesurfing",
    "hockey stop",
    "weaving basket",
    "playing shuffleboard",
    "ice fishing",
    "bookbinding",
    "playing laser tag",
    "dining",
    "casting fishing line",
    "delivering mail",
    "tobogganing",
    "washing hair",
    "square dancing",
    "playing american football",
    "exercising with an exercise ball",
    "krumping",
    "skydiving",
    "bathing dog",
    "hand washing clothes",
    "bouncing on bouncy castle",
    "making tea",
    "watching tv",
    "cleaning toilet",
    "playing darts",
    "jaywalking",
    "kicking field goal",
    "punching person (boxing)",
    "scrubbing face",
    "skiing mono",
    "huddling",
    "ice swimming",
    "playing xylophone",
    "unloading truck",
    "gargling",
    "twiddling fingers",
    "using a microscope",
    "sweeping floor",
    "passing soccer ball",
    "wading through mud",
    "cumbia",
    "cracking knuckles",
    "waiting in line",
    "cleaning gutters",
    "mixing colours",
    "playing paintball",
    "stretching arm",
    "using megaphone",
    "treating wood",
    "petting horse",
    "dyeing eyebrows",
    "drooling",
    "swimming butterfly stroke",
    "roller skating",
    "punching bag",
    "laying stone",
    "sharpening pencil",
    "pushing wheelbarrow",
    "catching or throwing softball",
    "laying tiles",
    "poking bellybutton",
    "riding scooter",
    "skiing crosscountry",
    "bending metal",
    "shooting basketball",
    "card stacking",
    "parasailing",
    "ski jumping",
    "waxing legs",
    "making cheese",
    "sanding floor",
    "playing cricket",
    "separating eggs",
    "shaving head",
    "carrying weight",
    "presenting weather forecast",
    "waking up",
    "picking apples",
    "mountain climber (exercise)",
    "popping balloons",
    "docking boat",
    "peeling apples",
    "tapping pen",
    "using inhaler",
    "petting animal (not cat)",
    "running on treadmill",
    "hugging baby",
    "juggling soccer ball",
    "snowkiting",
    "licking",
    "contorting",
    "cooking scallops",
    "inflating balloons",
    "gymnastics tumbling",
    "grinding meat",
    "playing drums",
    "playing maracas",
    "washing feet",
    "eating burger",
    "rock climbing",
    "carving pumpkin",
    "shucking oysters",
    "lunge",
    "shaping bread dough",
    "calligraphy",
    "extinguishing fire",
    "tickling",
    "swinging on something",
    "carving wood with a knife",
    "pushing cart",
    "sewing",
    "swimming with sharks",
    "baking cookies",
    "playing volleyball",
    "feeding birds",
    "baby waking up",
    "country line dancing",
    "tasting food",
    "clean and jerk",
    "playing netball",
    "building shed",
    "auctioning",
    "walking with crutches",
    "arranging flowers",
    "person collecting garbage",
    "wrapping present",
    "drinking shots",
    "spray painting",
    "passing American football (in game)",
    "sign language interpreting",
    "bandaging",
    "making a sandwich",
    "pull ups",
    "juggling balls",
    "playing poker",
    "climbing ladder",
    "cutting cake",
    "side kick",
    "laying decking",
    "fly tying",
    "cheerleading",
    "being excited",
    "dealing cards",
    "vacuuming car",
    "card throwing",
    "breaking glass",
    "shooting off fireworks",
    "egg hunting",
    "mushroom foraging",
    "cosplaying",
    "herding cattle",
    "weaving fabric",
    "pushing wheelchair",
    "swimming with dolphins",
    "drawing",
    "fencing (sport)",
    "swimming front crawl",
    "closing door",
    "sword swallowing",
    "eating doughnuts",
    "sipping cup",
    "throwing ball (not baseball or American football)",
    "waxing eyebrows",
    "jumping into pool",
    "cooking egg",
    "packing",
    "preparing salad",
    "winking",
    "gold panning",
    "spelunking",
    "swimming breast stroke",
    "jogging",
    "fixing bicycle",
    "filling cake",
    "embroidering",
    "texting",
    "pouring beer",
    "playing hand clapping games",
    "feeding fish",
    "bartending",
    "putting wallpaper on wall",
    "tackling",
    "sailing",
    "playing kickball",
    "paragliding",
    "laughing",
    "disc golfing",
    "bending back",
    "clam digging",
    "swinging baseball bat",
    "home roasting coffee",
    "moon walking",
    "dodgeball",
    "brush painting",
    "busking",
    "push up",
    "deadlifting",
    "shooting goal (soccer)",
    "hula hooping",
    "waxing back",
    "watering plants",
    "arresting",
    "burping",
    "picking blueberries",
    "making horseshoes",
    "entering church",
    "rolling eyes",
    "jumpstyle dancing",
    "making balloon shapes",
    "crossing river",
    "shaving legs",
    "high jump",
    "luge",
    "waxing chest",
    "carving marble",
    "using bagging machine",
    "applauding",
    "feeding goats",
    "riding elephant",
    "playing piano",
    "beatboxing",
    "water skiing",
    "zumba",
    "ironing hair",
    "cooking sausages (not on barbeque)",
    "using atm",
    "dancing macarena",
    "snorkeling",
    "playing cymbals",
    "sword fighting",
    "digging",
    "playing clarinet",
    "doing jigsaw puzzle",
    "shoveling snow",
    "cracking back",
    "washing dishes",
    "marriage proposal",
    "playing pan pipes",
    "changing oil",
    "playing organ",
    "pouring milk",
    "robot dancing",
    "letting go of balloon",
    "cleaning pool",
    "sieving",
    "arguing",
    "blowing leaves",
    "headbutting",
    "surfing crowd",
    "shot put",
    "passing American football (not in game)",
    "cleaning shoes",
    "lighting candle",
    "bench pressing",
    "unboxing",
    "reading newspaper",
    "breading or breadcrumbing",
    "yarn spinning",
    "geocaching",
    "pumping gas",
    "playing guitar",
    "alligator wrestling",
    "shuffling cards",
    "carrying baby",
    "historical reenactment",
    "blasting sand",
    "walking the dog",
    "photobombing",
    "drumming fingers",
    "riding a bike",
    "riding mechanical bull",
    "chopping wood",
    "playing ocarina",
    "playing beer pong",
    "pulling espresso shot",
    "capoeira",
    "milking goat",
    "massaging legs",
    "catching or throwing frisbee",
    "using a sledge hammer",
    "doing aerobics",
    "trapezing",
    "surfing water",
    "dunking basketball",
    "playing keyboard",
    "cooking chicken",
    "playing polo",
    "biking through snow",
    "playing rubiks cube",
    "juggling fire",
    "spinning poi",
    "playing pinball",
    "drop kicking",
    "canoeing or kayaking",
    "braiding hair",
    "shaking hands",
    "coughing",
    "playing nose flute",
    "playing trombone",
    "driving tractor",
    "adjusting glasses",
    "shredding paper",
    "making bubbles",
    "smoking hookah",
    "playing cello",
    "folding clothes",
    "making paper aeroplanes",
    "filling eyebrows",
    "making sushi",
    "bobsledding",
    "making pizza",
    "riding mule",
    "surveying",
    "dyeing hair",
    "mowing lawn",
    "combing hair",
    "cutting nails",
    "shopping",
    "playing rounders",
    "making jewelry",
    "walking through snow",
    "pole vault",
    "driving car",
    "decorating the christmas tree",
    "listening with headphones",
    "lifting hat",
    "climbing a rope",
    "wading through water",
    "slapping",
    "eating carrots",
    "cutting pineapple",
    "eating spaghetti",
    "tightrope walking",
    "standing on hands",
    "tossing salad",
    "ripping paper",
    "polishing furniture",
    "peeling potatoes",
    "checking tires",
    "putting on mascara",
    "curling hair",
    "bodysurfing",
    "playing violin",
    "smoking",
    "blowdrying hair",
    "frying vegetables",
    "using puppets",
    "making slime",
    "barbequing",
    "dumpster diving",
    "bottling",
    "setting table",
    "triple jump",
    "chopping meat",
    "doing nails",
    "playing lute",
    "tapping guitar",
    "smelling feet",
    "playing harmonica",
    "making a cake",
    "planting trees",
    "tying shoe laces",
    "javelin throw",
    "scuba diving",
    "laying bricks",
    "hitting baseball",
    "mosh pit dancing",
    "tasting beer",
    "windsurfing",
    "tap dancing",
    "sleeping",
    "testifying",
    "tying necktie",
    "putting on foundation",
    "brushing hair",
    "putting on shoes",
    "saluting",
    "singing",
    "crying",
    "marching",
    "visiting the zoo",
    "land sailing",
    "swing dancing",
    "yoga",
    "shaking head",
    "tying bow tie",
    "cutting apple",
    "hoverboarding",
    "rock scissors paper",
    "eating chips",
    "lighting fire",
    "petting cat",
    "flipping bottle",
    "planing wood",
    "pillow fight",
    "using a paint roller",
    "playing squash or racquetball",
    "massaging neck",
    "spinning plates",
    "coloring in",
    "falling off chair",
    "using a power drill",
    "roasting marshmallows",
    "catching fish",
    "snowboarding",
    "seasoning food",
    "sneezing",
    "poaching eggs",
    "playing marbles",
    "skipping stone",
    "doing sudoku",
    "assembling bicycle",
    "steer roping",
    "longboarding",
    "massaging person's head",
    "smoking pipe",
    "blowing bubble gum",
    "opening refrigerator",
    "trimming or shaving beard",
    "sanding wood",
    "reading book",
    "being in zero gravity",
    "sawing wood",
    "bulldozing",
    "playing basketball",
    "moving furniture",
    "playing dominoes",
    "welding",
    "cleaning windows",
    "putting on sari",
    "steering car",
    "needle felting",
    "clapping",
    "dancing ballet",
    "walking on stilts",
    "situp",
    "rope pushdown",
    "grooming cat",
    "base jumping",
    "skateboarding",
    "grooming dog",
    "playing trumpet",
    "playing saxophone",
    "contact juggling",
    "playing monopoly",
    "playing chess",
    "helmet diving",
    "bungee jumping",
    "eating watermelon",
    "opening door",
    "moving baby",
    "moving child",
    "cooking on campfire",
    "blowing out candles",
    "jumping bicycle",
    "high kick",
    "swimming backstroke",
    "staring",
    "pirouetting",
    "looking at phone",
    "grooming horse",
    "hopscotch",
    "crawling baby",
    "making latte art",
    "hammer throw",
    "archery",
    "milking cow",
    "golf driving",
    "tai chi",
    "playing bagpipes",
    "skipping rope",
    "playing ice hockey",
    "taking photo",
    "metal detecting",
    "finger snapping",
    "shuffling feet",
    "climbing tree",
    "curling (sport)",
    "capsizing",
    "holding snake",
    "putting on lipstick",
    "chewing gum",
    "dancing gangnam style",
    "plastering",
    "stacking dice",
    "fixing hair",
    "tying knot (not on a tie)",
    "smashing",
    "splashing water",
    "changing wheel (not on bike)",
    "putting in contact lenses",
    "kicking soccer ball",
    "high fiving",
    "silent disco",
    "building sandcastle",
    "uncorking champagne",
    "tie dying",
    "sucking lolly",
    "playing slot machine",
    "trimming trees",
    "dribbling basketball",
    "using a wrench",
    "throwing water balloon",
    "gospel singing in church",
    "opening bottle (not wine)",
    "acting in play",
    "rolling pastry",
    "sharpening knives",
    "answering questions",
    "folding paper",
    "knitting",
    "threading needle",
    "tango dancing",
    "waving hand",
    "playing piccolo",
    "sticking tongue out",
    "playing ping pong",
    "laying concrete",
    "ice climbing",
    "throwing discus",
    "installing carpet",
    "flint knapping",
    "cutting orange",
    "faceplanting",
    "ice skating",
    "eating ice cream",
    "cutting watermelon",
    "playing mahjong",
    "playing harp",
    "shouting",
    "jumping sofa",
    "sled dog racing",
    "wrestling",
    "water sliding",
    "throwing axe",
    "breaking boards",
    "riding camel"
]  

def real_glob(rglob):
    glob_list = braceexpand(rglob)
    files = []
    for g in glob_list:
        files = files + glob.glob(g)
    return files

def main():
    parser = argparse.ArgumentParser(description="Run model against images")
    parser.add_argument('--input-glob', default='data/kinetics_videos/jpg/yoga/0wHOYxjRmlw_000041_000051/image_000{41,42,43,44,45,46,47,48,49,50,41,42,43,44,45,46}.jpg',
                        help="inputs")
    parser.add_argument("--model", default="data/saved/r3d50_K_200ep.pth",
                        help="which model")
    args = parser.parse_args()


    model = resnet.generate_model(model_depth=50,
                                  n_classes=700,
                                  n_input_channels=3,
                                  shortcut_type="B",
                                  conv1_t_size=7,
                                  conv1_t_stride=1,
                                  no_max_pool=False,
                                  widen_factor=1.0)

    # model = load_pretrained_model(model, args.model, "resnet", 700)

    checkpoint = torch.load(args.model, map_location='cpu')
    arch = '{}-{}'.format("resnet", 50)
    assert arch == checkpoint['arch']

    if hasattr(model, 'module'):
        # I think this only for legacy models
        model.module.load_state_dict(checkpoint['state_dict'])
    else:
        model.load_state_dict(checkpoint['state_dict'])

    model.eval()

    image_clips = []
    files = real_glob(args.input_glob)
    print(files)
    for f in files:
        img = Image.open(f).convert("RGB")
        image_clips.append(img)

    mean = [0.4345, 0.4051, 0.3775]
    std = [0.2768, 0.2713, 0.2737]
    normalize = Normalize(mean, std)

    sample_size = 112

    spatial_transform = [Resize(sample_size)]
    spatial_transform.append(CenterCrop(sample_size))
    spatial_transform.append(ToTensor())
    spatial_transform.extend([ScaleValue(1), normalize])
    spatial_transform = Compose(spatial_transform)

    model_clips = []
    clip = [spatial_transform(img) for img in image_clips]
    model_clips.append(torch.stack(clip, 0).permute(1, 0, 2, 3))
    model_clips = torch.stack(model_clips, 0)

    print("Final", model_clips.shape)
    print("PEEK", model_clips[0,0,0,0:4,0:4])

    with torch.no_grad():
        outputs = model(model_clips)
        print(outputs[0][0:10])
        outputs = F.softmax(outputs, dim=1).cpu()

    sorted_scores, locs = torch.topk(outputs[0], k=3)

    print(locs[0])

    video_results = []
    for i in range(sorted_scores.size(0)):
        video_results.append({
            'label': magic_labels_700[locs[i].item()],
            'score': sorted_scores[i].item()
        })

    print(video_results)

if __name__ == '__main__':
    main()
